server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Headers de Segurança (OWASP A02:2025 - Security Misconfiguration)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;" always;


    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de arquivos estáticos para performance e PWA-like feeling
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|json)$ {
        expires 6m;
        access_log off;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    # Bloqueio de arquivos e diretórios ocultos (ex: .git, .env)
    location ~ /\. {
        deny all;
    }
}
